### ISSUE TITLE
Extract action-creators from reducer.js?

### ISSUE THREAD

**Issue by rjz** [dchasepdx/dnd-adventure-game#10]
Superficially, components depending on the `reducer.js` module appear to break with redux' [unidirectional data flow](http://redux.js.org/docs/basics/DataFlow.html#data-flow). We're actually only referencing the action-creators (and not the reducer itself), but we could clarify that by extracting actions to a separate `actions.js` (and [shared] constants to `constants.js`, and so on).

**Comment by dchasepdx** [comment]
Thanks for the feeback RJ. I've got a branch called reducer-cleanup that has the changes. I think I've got it right, but I'm still unsure how extracting the action-creators preserves the unidirectional data flow.

**Comment by rjz** [comment]
Looks awesome!

On flow: this is a functional no-op -- even before this change, the store was composed safely out of the components' reach. Moving the actions out just clarifies the (non-)relationship between components and the reducer for the casual observer's benefit.
